language: c

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.3

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq build-essential curl; fi

script:
    - export SKIPINSTALL=yes
    - export VERBOSE=yes
    - travis_wait 50 ./.travis-build.sh

after_script:
    - ./build-ffmpeg --cleanup
